# Site settings
title: Code Wrastlin
email: jim+howdy@jimsaunders.net
description: > # this means to ignore newlines until "baseurl:"
  Piledriving parsers & leg dropping lexers
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://jimsaunders.net # the base hostname & protocol for your site
enforce_ssl: jimsaunders.net
owner: JimDoesCode
social:    
  twitter: JimDoesCode
  github:  JimDoesCode
  stackoverflow: 1090118/jim-s

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
