# Site settings
title: Code Wrastlin
email: jimdoescode+howdy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Piledriving parsers and leg dropping lexers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jimdoescode.github.io" # the base hostname & protocol for your site
twitter_username: jimdoescode
github_username:  jimdoescode

# Build settings
markdown: kramdown
