# Site settings
title: Code Wrastlin&rsquo;
email: jimdoescode+howdy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Piledriving parsers and leg dropping lexers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jimdoescode.github.com" # the base hostname & protocol for your site
owner: JimDoesCode
social:    
  twitter: JimDoesCode
  github:  JimDoesCode
  stackoverflow: 1090118/jim-s

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
